[tool.briefcase]
project_name = "Canvas Demo"
bundle = "com.samesam"
version = "0.0.1"
url = "https://samesam.com/canvasdemo"
license = "BSD license"
author = 'Sam Same'
author_email = "sam@samesam.com"

[tool.briefcase.app.canvasdemo]
formal_name = "Canvas Demo"
description = "canvas of toga"
icon = "src/canvasdemo/resources/canvasdemo"
sources = ['src/canvasdemo']
requires = []


[tool.briefcase.app.canvasdemo.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.canvasdemo.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.canvasdemo.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.canvasdemo.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.canvasdemo.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
