[tool.briefcase]
project_name = "Calculator"
bundle = "calculator.com.samesam"
version = "0.0.1"
url = "https://samesam.com.calculator/calculator"
license = "BSD license"
author = 'Sam Shan'
author_email = "sam@samesam.com.calculator"

[tool.briefcase.app.calculator]
formal_name = "Calculator"
description = "One example of beeware"
icon = "src/calculator/resources/calculator"
sources = ['src/calculator']
requires = []


[tool.briefcase.app.calculator.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.calculator.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.calculator.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.calculator.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.calculator.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
