[tool.briefcase]
project_name = "Temperature Converter"
bundle = "temperature.com.samesam"
version = "0.0.1"
url = "https://samesam.com.temperature/temperatureconverter"
license = "BSD license"
author = 'Sam Shan'
author_email = "sam@samesam.com.temperature"

[tool.briefcase.app.temperatureconverter]
formal_name = "Temperature Converter"
description = "a Fahrenheit to Celsius converter"
icon = "src/temperatureconverter/resources/temperatureconverter"
sources = ['src/temperatureconverter']
requires = []


[tool.briefcase.app.temperatureconverter.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.temperatureconverter.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.temperatureconverter.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.temperatureconverter.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.temperatureconverter.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
